export const COLUMNS_NAME_EXCEL_REPORT_TRANSPORT_ADMIN = [
  { header: 'نام راننده', width: 20 },
  { header: 'مبایل راننده', width: 20 },
  { header: 'شناسه ثبت خرابی', width: 20 },
  { header: 'شماره پلاک', width: 20 },
  { header: 'کیلومتر', width: 20 },
  { header: 'ساعت ثبت گزارش توسط راننده', width: 20 },
  { header: 'تاریخ ثبت گزارش توسط راننده', width: 20 },
  { header: 'وضعیت تایید توسط مدیر لجستیک منطقه', width: 20 },
  { header: 'نظر مدیر ترابری', width: 20 },
  { header: 'تاریخ اعلام شده جهت اعزام به تعمیرگاه', width: 20 },
  { header: 'تاریخ تحویل به تعمیرگاه', width: 20 },
  { header: 'تاریخ تحویل به راننده', width: 20 },
  { header: 'قطعات تعمیری', width: 20 },
  { header: 'نظر تعمیرگاه', width: 20 },
  { header: 'ساعت ثبت نظر تعمیرگاه', width: 20 },
  { header: 'تاریخ ثبت نظر تعمیرگاه', width: 20 },
  { header: 'نظر مدیر لجستیک منطقه', width: 20 },
];
